SANTIAGO DIE MOREJÓN - 19/03/2026 - IA - Entregable 1 - Analisis de Datos

# Notebook 1: Análisis de Datos
En este notebook hare un análisis de los datasets de la competición IA2526 de Kanggle usando Pandas.

Comenzamos cargando la librería `pandas` y la librería `numpy`.

In [42]:
import numpy as np
import pandas as pd

## 1. Carga de datos

Cargamos los ficheros desde un repositorio público de GitHub que he creado donde subi los datasets de la competicion DATA_URL

In [43]:
!wget DATA_URL -O train.csv
!wget DATA_URL -O test.csv
!wget DATA_URL -O sample.csv

--2026-03-19 21:11:33--  DATA_URL
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 336082 (328K) [text/plain]
Saving to: ‘train.csv’

train.csv           100%[===================>] 328.21K  --.-KB/s    in 0.007s

2026-03-19 21:11:33 (48.7 MB/s) - ‘train.csv’ saved [336082/336082]

--2026-03-19 21:11:33--  DATA_URL
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 113736 (111K) [text/plain]
Saving to: ‘test.csv’

test.csv            100%[===================>] 111.07K  --.-KB/s    in 0.003s

2026-03-19 21:11:33 (33.6 MB/s) - ‘test.csv’ saved [113736/113736]

--2026-03-19 21:11:33--  DATA_URL
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 29588 (29K) [text/plain]
Saving to: ‘sample.csv’

sample.csv          100%[===================>]  28.89K  --.-KB/s    in 0s

2026-03-19 21:11:33 (86.3 MB/s) - ‘sample.csv’ saved [29588/29588]

Vamos a leer los datos, usando la función `read_csv` y almacenar el resultado en su DataFrame respectivo en traindf, testdf y sampledf

In [44]:
traindf  = pd.read_csv('train.csv')
testdf   = pd.read_csv('test.csv')
sampledf = pd.read_csv('sample.csv')

A continuación mostramos las 10 primeras instancias de los dataset usando el método `head`.

In [45]:
traindf.head(10)

          SL      EEG  BP   HR  CIRCULATION  ACTIVITY
0    4019.64 -1600.00  13   79          317         3
1    2191.03 -1146.08  20   54          165         2
2    2787.99 -1263.38  46   67          224         2
3    9545.98 -2848.93  26  138          554         4
4   14148.80 -2381.15  85  120          809         4
5    7336.79 -1699.80  22   95          427         5
6   24949.90 -3198.06  35  157         1519         3
7   39245.50 -2590.00  15  196         1885         3
8   59742.00 -5101.00  56  249         2826         0
9  140950.00 -1410.00  82  315         5844         4

In [46]:
testdf.head(10)

          SL      EEG   BP   HR  CIRCULATION
0   28146.00 -3670.00   29  194         1521
1   12064.90 -1796.28    8  105          765
2    3041.75 -1220.95   35   71          249
3    9918.52 -2570.00   44  154          587
4   26464.00 -3133.00   34  161         1523
5  193121.00 -6890.00   43  390         7459
6   47692.70 -5090.00   23  215         2188
7   51930.30 -5250.00   38  234         2464
8   80509.90 -5190.00   43  272         3539
9   30668.90 -3249.70  128  171         1747

In [47]:
sampledf.head(10)

   Id  Prediction
0   1           0
1   2           2
2   3           0
3   4           1
4   5           5
5   6           5
6   7           4
7   8           0
8   9           5
9  10           2

Vamos ahora a ver las dimensiones de los datos, los nombres de los descriptores y los tipos de los descriptores.

In [48]:
print(f'Train: {traindf.shape[0]} filas, {traindf.shape[1]} columnas')
print(f'Test:  {testdf.shape[0]} filas, {testdf.shape[1]} columnas')
print(f'Sample: {sampledf.shape[0]} filas, {sampledf.shape[1]} columnas')

Train: 11999 filas, 6 columnas
Test:  4383 filas, 5 columnas
Sample: 4383 filas, 2 columnas

In [49]:
print(f'Columnas de Train: {traindf.columns}')
print(f'Columnas de Test: {testdf.columns}')
print(f'Columnas de Sample: {sampledf.columns}')

Columnas de Train: Index(['SL', 'EEG', 'BP', 'HR', 'CIRCULATION', 'ACTIVITY'], dtype='object')
Columnas de Test: Index(['SL', 'EEG', 'BP', 'HR', 'CIRCULATION'], dtype='object')
Columnas de Sample: Index(['Id', 'Prediction'], dtype='object')

In [50]:
traindf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11999 entries, 0 to 11998
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SL           11999 non-null  float64
 1   EEG          11999 non-null  float64
 2   BP           11999 non-null  int64
 3   HR           11999 non-null  int64
 4   CIRCULATION  11999 non-null  int64
 5   ACTIVITY     11999 non-null  int64
dtypes: float64(2), int64(4)
memory usage: 562.6 KB

In [51]:
testdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4383 entries, 0 to 4382
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SL           4383 non-null   float64
 1   EEG          4383 non-null   float64
 2   BP           4383 non-null   int64
 3   HR           4383 non-null   int64
 4   CIRCULATION  4383 non-null   int64
dtypes: float64(2), int64(3)
memory usage: 171.3 KB

In [52]:
sampledf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4383 entries, 0 to 4382
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Id          4383 non-null   int64
 1   Prediction  4383 non-null   int64
dtypes: int64(2)
memory usage: 68.6 KB

Los tres datasets contienen únicamente variables numéricas

Voy a usar el método `describe` para mostrar las características estadísticas básicas de cada descriptor numérico.

In [53]:
traindf.describe()

,SL,EEG,BP,HR,CIRCULATION,ACTIVITY
count,1.199900e+04,1.199900e+04,11999.000000,11999.000000,11999.000000,11999.000000
mean,7.566022e+04,-2.229112e+04,58.483874,212.415535,2900.695058,2.368947
std,1.266692e+05,1.284765e+05,48.146245,130.375027,3789.822123,1.736608
min,4.222420e+01,-3.396800e+06,0.000000,33.000000,5.000000,0.000000
25%,1.006220e+04,-5.889500e+03,25.000000,120.000000,587.000000,0.000000
50%,3.243530e+04,-3.498580e+03,45.000000,180.000000,1626.000000,3.000000
75%,8.156320e+04,-2.290000e+03,79.000000,271.000000,3539.000000,4.000000
max,2.352450e+06,1.410000e+06,533.000000,981.000000,41819.000000,5.000000

In [54]:
testdf.describe()

                 SL           EEG           BP           HR   CIRCULATION
count  4.383000e+03  4.383000e+03  4383.000000  4383.000000   4383.000000
mean   7.464319e+04 -2.733101e+04    57.613735   209.131873   2876.947753
std    1.299711e+05  2.288913e+05    48.692051   128.761571   3923.458899
min    4.690760e+01 -1.262600e+07     0.000000    33.000000      5.000000
25%    9.950030e+03 -5.826810e+03    25.000000   118.000000    584.500000
50%    2.991810e+04 -3.413000e+03    43.000000   179.000000   1521.000000
75%    7.942745e+04 -2.297935e+03    77.000000   262.000000   3466.000000
max    2.426140e+06  1.440000e+05   435.000000   986.000000  52210.000000

In [55]:
sampledf.describe()

                Id   Prediction
count  4383.000000  4383.000000
mean   2192.000000     2.514944
std    1265.407444     1.714090
min       1.000000     0.000000
25%    1096.500000     1.000000
50%    2192.000000     3.000000
75%    3287.500000     4.000000
max    4383.000000     5.000000

## 2. Identificación de la Variable Objetivo

Antes de comenzar el análisis es importante identificar qué variable queremos predecir.

Comparando las columnas de `traindf` y `testdf`:

In [56]:
print(f'Variable objetivo: {set(traindf.columns) - set(testdf.columns)}')

Variable objetivo: {'ACTIVITY'}

La columna **ACTIVITY** está presente en `traindf` pero no en `testdf`. En problemas de aprendizaje supervisado, la columna que existe en train pero no en test es siempre lo que el modelo debe aprender a predecir.
## 3. Análisis de la Variable Objetivo

In [57]:
traindf['ACTIVITY'].value_counts()

ACTIVITY
0    3344
3    2625
4    2569
2    1849
5    1241
1     371
Name: count, dtype: int64

In [58]:
traindf['ACTIVITY'].value_counts(normalize=True) * 100

ACTIVITY
0    27.868989
3    21.876823
4    21.410118
2    15.409617
5    10.342529
1     3.091924
Name: proportion, dtype: float64

La variable objetivo `ACTIVITY` tiene 6 clases.

El dataset está moderadamente desbalanceado. Las clases 0, 3 y 4 tienen
casi el 71% de los datos, mientras que la clase 1 es tiene solo un 3.09% de los datos.

Este desbalance es importante tenerlo en cuenta en un futuro ya que el
clasificador podría tener dificultades para aprender a predecir correctamente
la clase 1 al tener tan pocos ejemplos de entrenamiento.

## 4. Análisis de los Descriptores Numéricos

### 4.1 Rango de valores de cada descriptor

Vamos a ver el rango (máximo - mínimo) de cada variable para entender en qué escala
se mueve cada una.

In [59]:
descriptores = ['SL', 'EEG', 'BP', 'HR', 'CIRCULATION']

print("Rango de cada descriptor:")
print(traindf[descriptores].max() - traindf[descriptores].min())

Rango de cada descriptor:
SL             2.352408e+06
EEG            4.806800e+06
BP             5.330000e+02
HR             9.480000e+02
CIRCULATION    4.181400e+04
dtype: float64

Las diferencias de escalas entre variables son muy grandes.
* `SL` y `EEG` se mueven en rangos de millones
* `CIRCULATION` en decenas de miles
* `BP` y `HR` tienen rangos de apenas cientos.

Esto nos indica que antes de usar modelos
sensibles a la escala como SVM, KNN o redes neuronales vamos a tener que escalar los datos

### 4.2 Valores extremos y anomalías

Podemos ordenar el dataset por el valor de un descriptor. Esto resulta util para buscar los extremos.

Se puede hacer con `sort_values` o con `apply`

In [60]:
traindf.sort_values(by='EEG', ascending=False).head()

             SL        EEG  BP   HR  CIRCULATION  ACTIVITY
9955   410917.0  1410000.0  59  473        14125         3
4561   142568.0   136000.0  52  315         5844         4
4429   112078.0    75300.0  49  235         4905         4
10580  113027.0    60000.0  40  322         4619         4
5471    35444.2    56000.0  28  234         1581         3

In [61]:
traindf.sort_values(by='HR', ascending=True).head()

            SL    EEG  BP  HR  CIRCULATION  ACTIVITY
11992  52.6785 -495.0   6  33            5         1
6708   50.0926 -575.0   6  33            5         2
9760   49.4916 -422.0   6  33            5         1
4063   57.7841 -192.0  92  33            5         3
91     52.5799 -430.0  92  33            5         4

In [62]:
traindf[descriptores].apply([np.min, np.max])

               SL        EEG   BP   HR  CIRCULATION
min  4.222420e+01 -3396800.0    0   33            5
max  2.352450e+06  1410000.0  533  981        41819

Viendo los extremos de todos los descriptores podemos detectar algo:
- `EEG` tiene valores negativos
- `BP` tiene un mínimo de 0 que es fisiológicamente imposible, por lo que vamos a verlo un poco mas a detalle

In [63]:
print(f"Registros con BP = 0: {(traindf['BP'] == 0).sum()}")
traindf[traindf['BP'] == 0]['ACTIVITY'].value_counts()

Registros con BP = 0: 17

ACTIVITY
4    5
3    5
5    3
2    3
0    1
Name: count, dtype: int64

Hay 17 registros con BP = 0, lo que representa apenas el 0.14% del total. Al ver su distribución por clase, se reparten entre varias actividades
distintas, lo que descarta que sea una característica propia de alguna actividad concreta. Al ser tan pocos lo más probable es que
sean errores de medición.

### 4.3 Estadísticas por clase de actividad
Lo más interesante es ver cómo varian los descriptores según la actividad que se está realizando. Para eso, se calculan la media `mean()` y la desviación típica `std()` de cada descriptor en los datasets. Si esos valores varían bastante entre clases, la señal tiene potencial para ayudar al clasificador a distinguir entre ellas; si son prácticamente iguales para todas las actividades, probablemente no aporte mucho.

In [64]:
traindf.groupby('ACTIVITY')[descriptores].mean()

                     SL           EEG         BP          HR  CIRCULATION
ACTIVITY
0         115259.184758 -10439.162174  72.426136  259.142644  4035.958433
1          18772.605988  -4347.166846  39.536388  117.024259   927.053908
2          50162.730818 -60734.703564  50.771769  170.239048  2051.018388
3          74155.773681 -14340.714846  51.204952  217.308190  2946.511619
4          63937.618342 -14377.418756  57.165045  199.950175  2613.268587
5          51402.210873 -35512.768840  56.196616  193.317486  2195.684932

In [65]:
traindf.groupby('ACTIVITY')[descriptores].std()

                     SL            EEG         BP          HR  CIRCULATION
ACTIVITY
0         181722.043441   98944.152707  68.027149  147.681077  4875.254325
1          26779.840130   40809.181559  46.324422   77.912161  1263.037025
2          84833.484930  218980.915250  35.280153  121.927624  2979.956043
3          96383.348617   95613.534080  34.308954  123.511765  3204.935414
4         105893.794064   90557.444977  37.257388  114.418725  3614.996102
5          73177.988380  148018.759820  35.365602  101.516783  2447.928577

* **Clase 0** tiene los valores más altos en `SL` (115 259.18), `HR` (259.14), `BP` (72.43)y `CIRCULATION` (4 035.96). En `EEG` (-10 439.16) tiene valores parecidos al resto. Es la clase con los valores de la mayoría de los descriptores más altos con respecto a las otras clases, por lo que será probablemente una clase fácil de identificar.

* **Clase 1** tiene los valores más bajos en todos los descriptores con `SL` (18 772.61),`HR` (117.02), `BP` (39.54) y `CIRCULATION` (927.05) y con el `EEG` menos negativo de todos (-4 347.17). Esa combinación la hace bastante identificable del resto.

* **Clase 2** se diferencia casi exclusivamente por su `EEG` extremadamente negativo (-60 734.70), muy por debajo del resto de clases. Sin embargo, su desviación típica en `EEG` es la mayor de toda la tabla (218 980.92), lo que nos dice que hay gran dispersión interna que puede complicar su identificación y clasificación.

* **Clases 3 y 4** son muy parecidas entre sí: `EEG` prácticamente idéntico
(-14 340.71 vs -14 377.42). `BP` (51.20 vs 57.16), `HR` (217.31 vs 199.95) y
`CIRCULATION` (2 946.51 vs 2 613.27) son descriptores que, considerando la
desviación, solapan mucho sus valores. El `SL` sí cambia algo (74 155.77 vs
63 937.62), pero sus desviaciones (96 383.35 y 105 893.79) son tan grandes que
esa diferencia es difícil de detectar.

* **Clase 5** tiene un `EEG` algo más negativo (-35 512.77) que las clases 3 y 4, lo que la aleja ligeramente, pero su desviación en `EEG` (148 018.76) es muy alta y no lo convierte en un separador fiable. En conjunto, las clases 3, 4 y 5 serán la fuente principal de errores del clasificador.

## 5. Preguntas sobre el Dataset

### Pregunta 1: ¿Es verdad que la media de HR de la clase 0 es superior a la media de HR del resto de clases combinadas?

In [66]:
traindf[traindf['ACTIVITY'] == 0]['HR'].mean()

np.float64(259.14264354066984)

In [67]:
traindf[traindf['ACTIVITY'] != 0]['HR'].mean()

np.float64(194.36175621028306)

Si, es verdad. La media de HR de la clase 0 es bastante superior al la del resto de clases combinadas.( 259.15 vs 194.37 )

### Pregunta 2: ¿Cuántos registros de la clase 2 tienen EEG por debajo de -100.000?

En el análisis anterior vimos que la clase 2 tiene el EEG más negativo y la mayor desviación típica. Queremos saber cuántos registros son realmente extremos.

In [68]:
clase2 = traindf[traindf['ACTIVITY'] == 2]
extremos = clase2[clase2['EEG'] < -100000]

In [69]:
print(len(extremos))
print(f'{len(extremos) / len(clase2) * 100:.2f}%')

122
6.60%

Solo 122 registros de la clase 2 tienen EEG por debajo de -100.000, que es solo el 6.60% de esa clase. Esto significa que aunque la media de EEG de la clase 2 es la mas negativa, la  mayoria de sus registros no son tan extremos. La desviación típica que observamos en el apartado 4.3 se debe a unos pocos valores muy extremos, lo que cambia nuestra anterior suposicion que identificar la clase 2 seria algo mas sencillo.

### Pregunta 3: ¿Cuántos registros de la clase 4 tienen valores de SL similares a de los de la clase 3?
Comprobamos si los registros de clase 3 y 4 se solapan para el descriptor SL.

In [70]:
q25 = traindf[traindf['ACTIVITY'] == 3]['SL'].quantile(0.25)
q75 = traindf[traindf['ACTIVITY'] == 3]['SL'].quantile(0.75)
c4 = traindf[
    (traindf['ACTIVITY'] == 4) &
    (traindf['SL'] >= q25) &
    (traindf['SL'] <= q75)]

In [71]:
print(f'Rango : [{q25:.2f}, {q75:.2f}]')
print(len(c4))
print(f'Porcentaje:{len(c4) / len(traindf[traindf["ACTIVITY"]==4]) * 100:.1f}%')

Rango : [12048.10, 90468.90]
1377
Porcentaje:53.6%

El 53.6% de los registros de la clase 4 caen dentro del rango de la clase 3 [12.048, 90.469] del descriptor SL

###Pregunta 4: ¿Los registros con CIRCULATION muy alta (> percentil 90) de que clase son mayoritariamente?

In [72]:
q90 = traindf['CIRCULATION'].quantile(0.90)
preg4 = traindf[traindf['CIRCULATION'] > q90]

In [73]:
print(f'Total: {len(preg4)}')

Total: 1170

In [74]:
print(preg4['ACTIVITY'].value_counts())

ACTIVITY
0    598
3    240
4    191
5     79
2     62
Name: count, dtype: int64

De los 1170 registros con CIRCULATION por encima del percentil 90, 598 pertenecen a la clase 0, lo que representa el 51.1% del total. Esto confirma lo que ya veiamos con las medias, la clase 0 tiene la mayoría de los valores extremos de CIRCULATION

### Pregunta 5: ¿Cuántos registros tienen HR superior a 300? ¿A qué clase pertenecen mayoritariamente?

In [75]:
preg5 = traindf[traindf['HR'] > 300]

In [76]:
print(len(preg5))
print(preg5['ACTIVITY'].value_counts())

2364
ACTIVITY
0    1075
3     507
4     376
2     265
5     140
1       1
Name: count, dtype: int64

Hay 2364 registros con HR superior a 300, de ellos 1075 pertenecen a la clase 0, siendo con diferencia la clase mayoritaria en este grupo.

## 6. Conclusión

En este notebook hemos realizado un análisis  completo del dataset de la competición IA2526. Los puntos más relevantes que hemos extraído son:

- El problema consiste en clasificar 6 tipos de actividad a partir de 5 señales fisiológicas (`SL`, `EEG`, `BP`, `HR`, `CIRCULATION`), todas numéricas.
- El dataset está moderadamente desbalanceado, con la clase 1 siendo claramente minoritaria (3.09%).
- Las diferencias de escala entre descriptores son muy grandes, por lo que será necesario escalar los datos antes de entrenar ciertos modelos.
- Las clases 0 y 1 son las más fáciles de identificar al tener valores claramente distintos al resto. Las clases 3, 4 y 5 serán la principal fuente de errores del clasificador al solaparse mucho entre sí.

En el siguiente notebook continuaremos con la visualización de los datasets, lo que nos permitirá confirmar visualmente las hipótesis planteadas aquí.